# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 12:54
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_adress', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=45)),
                ('neighborhood', models.CharField(max_length=45)),
                ('number', models.CharField(max_length=4)),
                ('complement', models.CharField(max_length=45)),
                ('zip_code', models.CharField(max_length=8)),
                ('public_place', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Bank_accounts',
            fields=[
                ('id_bank_accounts', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20)),
                ('agency_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Bank_names',
            fields=[
                ('bank_number', models.IntegerField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Bank_names',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cnpj', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('corporate_name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=45)),
                ('agreement', models.BooleanField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Address')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id_hiring', models.AutoField(primary_key=True, serialize=False)),
                ('contracted_at', models.DateTimeField(auto_now_add=True)),
                ('contract_end', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
            options={
                'db_table': 'Hiring',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id_requirements', models.AutoField(primary_key=True, serialize=False)),
                ('work_shift', models.CharField(max_length=20)),
                ('workload', models.IntegerField()),
                ('additional_info', models.CharField(max_length=500)),
                ('minimun_period', models.IntegerField()),
            ],
            options={
                'db_table': 'Requirements',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('destiny', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('feedback', models.CharField(max_length=500)),
                ('cnpj_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
                ('hiring_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hiring')),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{11}$')])),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=45)),
                ('regular_student', models.BooleanField()),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Vacant_job',
            fields=[
                ('id_vacancy', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Vacant_jobs',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Student')),
                ('time_desired', models.IntegerField()),
                ('work_shift', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=45)),
                ('additional_info', models.CharField(max_length=900)),
                ('semester', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.File')),
            ],
            options={
                'db_table': 'Curriculum',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='hiring',
            name='id_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
        migrations.AddField(
            model_name='hiring',
            name='id_vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Vacant_job'),
        ),
        migrations.AddField(
            model_name='bank_accounts',
            name='bank_names_bank_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bank_names'),
        ),
        migrations.AddField(
            model_name='bank_accounts',
            name='student_cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student'),
        ),
    ]
