# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 20:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, unique=True)),
                ('path_arquivo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.IntegerField()),
                ('numero_agencia', models.IntegerField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Banco')),
            ],
            options={
                'db_table': 'conta_bancaria',
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_adicional', models.TextField(max_length=500)),
                ('arquivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Arquivo')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('conveniada', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('estudante_regular', models.BooleanField()),
                ('matricula', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^d{9}$')])),
                ('semestre', models.IntegerField()),
                ('universidade', models.CharField(max_length=45)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefone', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='telefone',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cv',
            name='turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Turno'),
        ),
    ]
