# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170603_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivo',
            options={'verbose_name': 'Arquivo', 'verbose_name_plural': 'Arquivos'},
        ),
        migrations.AlterModelOptions(
            name='banco',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='estudante',
            options={'verbose_name': 'Estudante', 'verbose_name_plural': 'Estudantes'},
        ),
        migrations.AlterModelOptions(
            name='telefone',
            options={'verbose_name': 'Telefone', 'verbose_name_plural': 'Telefones'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AlterModelTable(
            name='arquivo',
            table='arquivo',
        ),
        migrations.AlterModelTable(
            name='banco',
            table='banco',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
        migrations.AlterModelTable(
            name='cv',
            table='cv',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='empresa',
        ),
        migrations.AlterModelTable(
            name='estudante',
            table='estudante',
        ),
        migrations.AlterModelTable(
            name='telefone',
            table='telefone',
        ),
        migrations.AlterModelTable(
            name='turno',
            table='turno',
        ),
    ]
